[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn kislevsmart.wsgi:application --workers 2 --threads 4 --worker-class gthread --timeout 120 --bind 0.0.0.0:$PORT"
