# Generated by Django 3.2.25 on 2025-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_torre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apartamento',
            field=models.CharField(blank=True, default='', help_text='Número de apartamento', max_length=10),
        ),
    ]
