# Generated by Django 5.1.15 on 2026-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntoresidencial',
            name='link_pago',
            field=models.URLField(blank=True, help_text='Link del portal de pagos para este conjunto', max_length=500, null=True),
        ),
    ]
