# Generated by Django 5.1.15 on 2026-04-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_link_pago_conjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_saas_owner',
            field=models.BooleanField(default=False, help_text='Propietario del SaaS — accede a todos los conjuntos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Fuerza cambio de contraseña en el próximo login'),
        ),
    ]
