# Generated by Django 5.1.15 on 2026-04-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_saas_owner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntoresidencial',
            name='tipo_distribucion',
            field=models.CharField(choices=[('torre_apto', 'Torre / Apartamento'), ('interior_apto', 'Interior / Apartamento'), ('bloque_apto', 'Bloque / Apartamento'), ('manzana_casa', 'Manzana / Casa'), ('solo_apto', 'Solo apartamento (sin agrupación)'), ('solo_casa', 'Solo casa (sin agrupación)')], default='torre_apto', help_text='Cómo está distribuido físicamente el conjunto', max_length=20),
        ),
    ]
