# Generated by Django 5.1.15 on 2026-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_distribucion_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_arrendatario',
            field=models.BooleanField(default=False, help_text='Si es True, el usuario es arrendatario (user_type=propietario pero no dueño del inmueble)'),
        ),
    ]
