# Generated by Django 5.1.15 on 2026-04-20 03:32

from django.db import migrations, models

# Horarios de ejemplo para conjuntos existentes.
# Clave: nombre exacto del conjunto (normalizado a minúsculas para comparar).
HORARIOS_EJEMPLO = {
    'kislev': (
        'Lunes a viernes: 8:00 a.m. – 5:00 p.m.\n'
        'Sábados: 9:00 a.m. – 12:00 m.\n'
        'Domingos y festivos: Cerrado'
    ),
    'oliva madrid': (
        'Lunes y martes: 8:00 a.m. – 6:00 p.m.\n'
        'Miércoles: 8:00 a.m. – 4:00 p.m.\n'
        'Jueves y viernes: 8:00 a.m. – 6:00 p.m.\n'
        'Sábados: 9:00 a.m. – 1:00 p.m.\n'
        'Domingos y festivos: Cerrado'
    ),
    'puerto hayuelos 1': (
        'Lunes a jueves: 7:30 a.m. – 5:30 p.m.\n'
        'Viernes: 7:30 a.m. – 4:00 p.m.\n'
        'Sábados: 8:00 a.m. – 12:00 m.\n'
        'Domingos y festivos: Cerrado'
    ),
}

HORARIO_GENERICO = (
    'Lunes a viernes: 8:00 a.m. – 5:00 p.m.\n'
    'Sábados: 9:00 a.m. – 12:00 m.\n'
    'Domingos y festivos: Cerrado'
)


def poblar_horarios(apps, schema_editor):
    ConjuntoResidencial = apps.get_model('accounts', 'ConjuntoResidencial')
    for c in ConjuntoResidencial.objects.all():
        if not c.horario_atencion:
            key = c.nombre.lower().strip()
            c.horario_atencion = HORARIOS_EJEMPLO.get(key, HORARIO_GENERICO)
            c.save(update_fields=['horario_atencion'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_es_arrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntoresidencial',
            name='horario_atencion',
            field=models.TextField(blank=True, default='', help_text='Horario de atención de la administración (texto libre, ej: Lunes a viernes 8–17 h).'),
        ),
        migrations.RunPython(poblar_horarios, migrations.RunPython.noop),
    ]
