"""
Django settings for kislevsmart project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@@i8x+#kv7)iilb$kc3^zpgf+m^%)&_a!x!8bb+b2!m0f_*61k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'kislevsmart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'kislevsmart.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'kislevsmart', 'templates'),
            os.path.join(BASE_DIR, 'accounts', 'templates'),  # Agregar la carpeta de plantillas de accounts
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'kislevsmart.wsgi.application'



SESSION_ENGINE = 'django.contrib.sessions.backends.db'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto
)

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'login',
        'USER': 'yagami',
        'PASSWORD': 'Ipsos2012*',
        'HOST': 'localhost',  # O el host que uses
        'PORT': '5432',       # Puerto predeterminado de PostgreSQL
    }
}

AUTH_USER_MODEL = 'accounts.Usuario'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


LOGIN_URL = '/accounts/login/'
ESSION_ENGINE = 'django.contrib.sessions.backends.db'


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Carpeta global
    BASE_DIR / "accounts" / "static",  # Archivos estáticos específicos de 'accounts'
    BASE_DIR / "kislevsmart" / "static",  # Archivos estáticos específicos de 'kislevsmart'
]

# Directorio donde se recopilan todos los archivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Configuración de Email con SendGrid
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = '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'
DEFAULT_FROM_EMAIL = 'mariax.ceb@gmail.com'  # El email que configuraste en SendGrid
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Ponlo en False cuando quieras enviar emails reales
# Configuración adicional recomendada
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS = True
SENDGRID_REPLY_TO = DEFAULT_FROM_EMAIL
SENDGRID_MERGE_FIELD_FORMAT = None
SENDGRID_CATEGORIES = ['notificaciones_servicios']


# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console'],
            'level': 'WARNING',  # Cambiado a WARNING para reducir logs
        },
        'tu_app': {  # Reemplaza con el nombre de tu app
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



import environ

# Inicializa django-environ
env = environ.Env()
environ.Env.read_env()