"""
Django settings for kislevsmart project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import environ
import os
from pathlib import Path
import dj_database_url

# Inicialización de environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-@@i8x+#kv7)iilb$kc3^zpgf+m^%)&_a!x!8bb+b2!m0f_*61k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

# Configuraciones de Seguridad
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_BROWSER_XSS_FILTER = env.bool('SECURE_BROWSER_XSS_FILTER', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = env.bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuraciones de Cookie
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Cambiado a 'Lax' para mejor compatibilidad con Railway
CSRF_COOKIE_SAMESITE = 'Lax'

# Configuraciones adicionales de seguridad
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Configuración de hosts permitidos para producción
    ALLOWED_HOSTS = [
        '.railway.app',
        'localhost',
        '127.0.0.1',
        '[::1]',
        # Añade aquí tu dominio personalizado si lo tienes
    ]
else:
    ALLOWED_HOSTS = ['*']
    
    


# Configuración de sesión mejorada
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Añadido para mayor seguridad

# Configuraciones de caché existentes
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}    



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'kislevsmart',
    'whitenoise.runserver_nostatic',
]

# Configuración de middleware con orden optimizado
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kislevsmart.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'kislevsmart', 'templates'),
            os.path.join(BASE_DIR, 'accounts', 'templates'),
            os.path.join(BASE_DIR, 'templates'),  # Añade esta línea
            os.path.join(BASE_DIR),  # Añade esta línea si el template está en la raíz
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'kislevsmart.wsgi.application'





SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_CACHE_ALIAS = 'default'
SESSION_SAVE_EVERY_REQUEST = True


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto
)

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases



# Database configuration
if os.getenv('DATABASE_URL', None):
    # Configuración para Railway (producción)
    import dj_database_url
    DATABASES = {
        'default': {
            **dj_database_url.config(
                default=os.getenv('DATABASE_URL'),
                conn_max_age=0,  # Desactivar conexiones persistentes
            ),
            'ATOMIC_REQUESTS': True,  # Hace que todas las vistas sean atómicas por defecto
            'OPTIONS': {
                'isolation_level': 1,  # READ COMMITTED isolation level
                'connect_timeout': 10,  # Timeout de conexión en segundos
            },
            'TEST': {
                'MIRROR': 'default',   # Para tests
            },
        }
    }
else:
    # Configuración para desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'login',
            'USER': 'yagami',
            'PASSWORD': 'Ipsos2012*',
            'HOST': 'localhost',
            'PORT': '5432',
            'ATOMIC_REQUESTS': True,
            'CONN_MAX_AGE': 0,  # Desactivar conexiones persistentes
            'OPTIONS': {
                'isolation_level': 1,  # READ COMMITTED isolation level
                'connect_timeout': 10,
            },
        }
    }

# Configuración adicional recomendada para manejo de transacciones
DATABASE_ROUTERS = []

# Configuración de caché para mejor manejo de sesiones y transacciones
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}




#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'login',
#        'USER': 'yagami',
#        'PASSWORD': 'Ipsos2012*',
#        'HOST': 'localhost',  # O el host que uses
#        'PORT': '5432',       # Puerto predeterminado de PostgreSQL
#    }
#}

AUTH_USER_MODEL = 'accounts.Usuario'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# Configuración de internacionalización
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Configuración adicional para manejo de fechas y horas
DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'
TIME_FORMAT = 'H:i:s'

# Configuración de formato para fechas en español
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',
    '%d-%m-%Y',
    '%Y-%m-%d',
]

TIME_INPUT_FORMATS = [
    '%H:%M:%S',
    '%H:%M',
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M:%S',
    '%d/%m/%Y %H:%M',
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d %H:%M',
]

# Configuración para manejo de zonas horarias
USE_DEPRECATED_PYTZ = False  # Para versiones más nuevas de Django
TIMEZONE_COOKIE_NAME = 'timezone'
TIMEZONE_COOKIE_AGE = 2592000  # 30 días

# Configuración de locale
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = [
    ('es-mx', 'Español de México'),
    ('es-co', 'Español de Colombia'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


LOGIN_URL = '/accounts/login/'
ESSION_ENGINE = 'django.contrib.sessions.backends.db'


# Configuración de archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'kislevsmart', 'static'),  # Archivos estáticos del proyecto
    os.path.join(BASE_DIR, 'accounts', 'static'),      # Archivos estáticos de accounts
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'




# Configuración de archivos media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Email con SendGrid
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='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')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='david.rojas@kislev.net.co')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS = True
SENDGRID_REPLY_TO = 'david.rojas@kislev.net.co'  # El mismo correo verificado



# Configuración de seguridad adicional para producción
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_PROXY_SSL_HEADER = None

# Configuración de Email con SendGrid
#EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
#SENDGRID_API_KEY = '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'
#DEFAULT_FROM_EMAIL = 'mariax.ceb@gmail.com'  # El email que configuraste en SendGrid
#SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Ponlo en False cuando quieras enviar emails reales
# Configuración adicional recomendada
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS = True
SENDGRID_REPLY_TO = DEFAULT_FROM_EMAIL
SENDGRID_MERGE_FIELD_FORMAT = None
SENDGRID_CATEGORIES = ['notificaciones_servicios']


# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}


