# Generated by Django 3.2.25 on 2024-10-16 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_creador', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('cedula', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
                ('nombre_log', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
