# Generated by Django 3.2.25 on 2024-10-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='numper',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nombre_log',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
