# Generated by Django 3.2.25 on 2024-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('kislevsmart', '0004_visitantevehicular'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueaderoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('techado', models.BooleanField(default=False)),
                ('tiene_anclaje', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial')),
            ],
            options={
                'verbose_name': 'Parqueadero de Moto',
                'verbose_name_plural': 'Parqueaderos de Motos',
                'ordering': ['numero'],
                'unique_together': {('conjunto', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ParqueaderoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('techado', models.BooleanField(default=False)),
                ('dimensiones', models.CharField(blank=True, help_text='Ejemplo: 2.5m x 5m', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial')),
            ],
            options={
                'verbose_name': 'Parqueadero de Carro',
                'verbose_name_plural': 'Parqueaderos de Carros',
                'ordering': ['numero'],
                'unique_together': {('conjunto', 'numero')},
            },
        ),
    ]
