# Generated by Django 3.2.25 on 2024-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0005_parqueaderocarro_parqueaderomoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parqueaderocarro',
            options={'verbose_name': 'Parqueadero de Carro', 'verbose_name_plural': 'Parqueaderos de Carros'},
        ),
        migrations.AlterModelOptions(
            name='parqueaderomoto',
            options={'verbose_name': 'Parqueadero de Moto', 'verbose_name_plural': 'Parqueaderos de Motos'},
        ),
        migrations.AddField(
            model_name='parqueaderocarro',
            name='total_espacios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parqueaderomoto',
            name='total_espacios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='parqueaderocarro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parqueaderomoto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parqueaderocarro',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='parqueaderocarro',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='parqueaderocarro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='parqueaderocarro',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='parqueaderocarro',
            name='techado',
        ),
        migrations.RemoveField(
            model_name='parqueaderomoto',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='parqueaderomoto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='parqueaderomoto',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='parqueaderomoto',
            name='techado',
        ),
        migrations.RemoveField(
            model_name='parqueaderomoto',
            name='tiene_anclaje',
        ),
    ]
