# Generated by Django 3.2.25 on 2026-04-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
        ('kislevsmart', '0006_auto_20241101_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='visitantevehicular',
            name='usuario',
        ),
        migrations.AddField(
            model_name='visitante',
            name='conjunto',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial'),
        ),
        migrations.AddField(
            model_name='visitantevehicular',
            name='conjunto',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial'),
        ),
    ]
