# Generated by Django 3.2.25 on 2026-04-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_usuario_apartamento'),
        ('kislevsmart', '0007_fix_visitante_fk_conjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('visitante_creado', 'Visitante creado'), ('qr_validado', 'QR validado'), ('qr_invalido', 'QR inválido'), ('reserva_creada', 'Reserva creada'), ('reserva_fallida', 'Reserva fallida'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.conjuntoresidencial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'audit_log',
                'ordering': ['-fecha'],
            },
        ),
    ]
