# Generated by Django 3.2.25 on 2026-04-02 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kislevsmart', '0008_add_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Administración mayo 2026', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.PositiveIntegerField(help_text='Valor en COP')),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('extraordinaria', 'Extraordinaria')], default='mensual', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='accounts.conjuntoresidencial')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuotas',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.PositiveIntegerField(help_text='Valor en COP')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('comprobante', models.CharField(blank=True, help_text='Número de comprobante o referencia', max_length=100)),
                ('fecha_pago', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='kislevsmart.cuota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
                'unique_together': {('cuota', 'propietario')},
            },
        ),
    ]
