# Generated by Django 5.1.15 on 2026-04-03 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
        ('kislevsmart', '0009_add_cuota_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial'),
        ),
    ]
