# Generated by Django 5.1.15 on 2026-04-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
        ('kislevsmart', '0010_add_conjunto_to_sala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='novedades/imagenes/')),
                ('contenido', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to=settings.AUTH_USER_MODEL)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='accounts.conjuntoresidencial')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'novedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='kislevsmart.novedad')),
            ],
            options={
                'db_table': 'comentarios_novedad',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='novedades/archivos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='kislevsmart.novedad')),
            ],
            options={
                'db_table': 'archivos_novedad',
            },
        ),
    ]
