# Generated by Django 5.1.15 on 2026-04-03 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0011_add_novedades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='kislevsmart.novedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_novedad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes_novedad',
                'unique_together': {('novedad', 'usuario')},
            },
        ),
    ]
