# Generated by Django 5.1.15 on 2026-04-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0012_add_like_novedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(default='Mantenimiento', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_sala', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='kislevsmart.sala')),
            ],
            options={
                'verbose_name': 'Bloqueo de Sala',
                'verbose_name_plural': 'Bloqueos de Salas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
