# Generated by Django 5.1.15 on 2026-04-03 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_apartamento'),
        ('kislevsmart', '0013_bloqueo_sala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.CharField(max_length=10)),
                ('empresa', models.CharField(choices=[('envia', 'Envia'), ('coordinadora', 'Coordinadora'), ('servientrega', 'Servientrega'), ('interrapidisimo', 'Interrapidísimo'), ('deprisa', 'Deprisa'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('amazon', 'Amazon Logistics'), ('mercadolibre', 'Mercado Libre'), ('tcc', 'TCC'), ('rappi', 'Rappi'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: caja grande, sobre, etc.', max_length=200)),
                ('codigo', models.CharField(max_length=6)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=15)),
                ('destinatario_nombre', models.CharField(blank=True, max_length=100)),
                ('destinatario_telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='accounts.conjuntoresidencial')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_entregados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_registrados', to=settings.AUTH_USER_MODEL)),
                ('torre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='accounts.torre')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
