# Generated by Django 5.1.15 on 2026-04-06 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0015_reserva_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='NovedadVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_en', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='kislevsmart.novedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'novedades_vistas',
                'unique_together': {('novedad', 'usuario')},
            },
        ),
    ]
