# Generated by Django 5.1.15 on 2026-04-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_link_pago_conjunto'),
        ('kislevsmart', '0016_novedad_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=10)),
                ('minutos_gracia', models.PositiveIntegerField(default=0, help_text='Minutos gratuitos antes de comenzar a cobrar')),
                ('valor_hora', models.DecimalField(decimal_places=0, default=0, help_text='Valor por hora en COP después de la gracia', max_digits=10)),
                ('fraccion_minutos', models.PositiveIntegerField(default=60, help_text='Fracción mínima de cobro en minutos (ej: 30 = cobrar por medias horas)')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_parqueadero', to='accounts.conjuntoresidencial')),
            ],
            options={
                'db_table': 'config_parqueadero',
                'unique_together': {('conjunto', 'tipo_vehiculo')},
            },
        ),
    ]
