# Generated by Django 5.1.15 on 2026-04-15 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_link_pago_conjunto'),
        ('kislevsmart', '0017_config_parqueadero'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_propietario', models.EmailField(db_index=True, max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('cedula', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('numper', models.CharField(default='1', max_length=20)),
                ('tipo', models.CharField(choices=[('peatonal', 'Peatonal'), ('vehicular', 'Vehicular')], default='peatonal', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.conjuntoresidencial')),
            ],
            options={
                'verbose_name': 'Visitante Guardado',
                'verbose_name_plural': 'Visitantes Guardados',
                'ordering': ['-creado'],
            },
        ),
    ]
