# Generated by Django 5.1.15 on 2026-04-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0019_log_envio_config_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configglobal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logenvio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
