# Generated by Django 5.1.15 on 2026-04-24 20:03

from django.db import migrations


def crear_parking_defaults(apps, schema_editor):
    """
    Para cada conjunto que no tenga ParqueaderoCarro o ParqueaderoMoto,
    crea registros con valores por defecto: 20 carros, 10 motos.
    Se ejecuta al hacer migrate en Railway.
    """
    ConjuntoResidencial = apps.get_model('accounts', 'ConjuntoResidencial')
    ParqueaderoCarro = apps.get_model('kislevsmart', 'ParqueaderoCarro')
    ParqueaderoMoto = apps.get_model('kislevsmart', 'ParqueaderoMoto')

    for conjunto in ConjuntoResidencial.objects.all():
        ParqueaderoCarro.objects.get_or_create(
            conjunto=conjunto,
            defaults={'total_espacios': 20},
        )
        ParqueaderoMoto.objects.get_or_create(
            conjunto=conjunto,
            defaults={'total_espacios': 10},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0021_add_db_indexes'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_parking_defaults, migrations.RunPython.noop),
    ]
