# Generated by Django 5.1.15 on 2026-04-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kislevsmart', '0022_default_parking_espacios'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='numero_guia',
            field=models.CharField(blank=True, help_text='Número de guía o tracking del operador', max_length=60),
        ),
    ]
